### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by Velisariy** [snooppr/snoop#2]
Traceback (most recent call last):
  File "C:\Users\serge\Downloads\snoop-master\snoop.py", line 762, in <module>
    main()
  File "C:\Users\serge\Downloads\snoop-master\snoop.py", line 428, in main
    cop = copyright.read()
  File "C:\Users\serge\AppData\Local\Programs\Python\Python37\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1426: character maps to <undefined>

**Comment by Velisariy** [comment]
а, или только на OS GNU/Linux  гарантируется работа?

**Comment by snooppr** [comment]
Project Snoop работает на OS GNU/Linux & Android/Termux.
