### ISSUE TITLE
ValueError: Namespace Gst not available```

### ISSUE THREAD

**Issue by wanghaisheng** [snooppr/snoop#26]
```root@ubuntu-s-1vcpu-1gb-ams3-01:~/snoop# python3 snoop.py  sexdoll

  ___|                          
\___ \  __ \   _ \   _ \  __ \  
      | |   | (   | (   | |   | 
_____/ _|  _|\___/ \___/  .__/  
                         _|     v1.1.8_rus

#Пример:
 cd ~/snoop
 python3 snoop.py -h #справка по функциям ПО
 python3 snoop.py -t 9 username #поиск user-a
=============================================


загружена база: data.json:: 859_Websites
[*] разыскиваем: < sexdoll >
[-] 0k_clan: Увы!
[-] 11x2: Увы!
[-] 1337x: Увы!
[-] 1x: Увы!
[-] 1xforum: Увы!
[-] 2Dimensions: Увы!
[-] 2berega_spb: Увы!
[-] 33bru: Увы!
[-] 3dnews: Увы!
[-] 4cheat: Увы!
[-] Ошибка соединения: 4gameforum
[*] разыскиваем: < sexdoll >
[-] 0k_clan: Увы!
[-] 11x2: Увы!
[-] 1337x: Увы!
[-] 1x: Увы!
[-] 1xforum: Увы!
[-] 2Dimensions: Увы!
[-] 2berega_spb: Увы!
[-] 33bru: Увы!
[-] 3dnews: Увы!
[-] 4cheat: Увы!
🇷🇺  4gameforum: https://4gameforum.com/members/?username=sexdoll
[-] 4pda: *Пропуск
[-] 4stor: Увы!
🇺🇸  500px: https://500px.com/sexdoll
[-] 7Cups: Увы!
[-] 7dach: Увы!
[-] Aback: Увы!
🇺🇸  About.me: https://about.me/sexdoll
[-] Academia.edu: Увы!
[-] Advancedcustomfields: Увы!
[-] Advego: Увы!
[-] Airliners: Увы!
[-] Akniga: Увы!
[-] Alabay: Увы!
[-] Alik.cz: Увы!
[-] Allhockey: Увы!
[-] Allmylinks: Увы!
[-] Allods: Увы!
[-] Allrecipes: Увы!
[-] Alltrails: Увы!
[-] Alternativeto: Увы!
[-] Amirite: Увы!
[-] Anapakurort: Увы!
[-] Anarcho-punk: Увы!
[-] Androidforums: Увы!
[-] Angara: Увы!
[-] Angelgothics: Увы!
[-] Anobii: Увы!
[-] Antichat: Увы!
[-] Antipunk: Увы!
[-] Ap-pro: Увы!
[-] AppleDeveloper: Увы!
🇵🇹  Aptoide: https://sexdoll.en.aptoide.com/app
[-] Aqa: Увы!
🇷🇺  ArcheageRU: https://aa.mail.ru/forums/member.php?username=sexdoll
🇺🇸  Archive.org: https://archive.org/details/@sexdoll
[-] Archiveofourown: Увы!
[-] Archlinux: Увы!
[-] Arhrock: Увы!
[-] Ariva: Увы!
[-] Armchairgm: Увы!
[-] ArmoredRU: Увы!
🇺🇸  Armorgames: https://armorgames.com/user/sexdoll
[-] Arsenal-mania: Увы!
[-] Artpersona: Увы!
[-] Asciinema: Увы!
🇱🇻  AskFM: https://ask.fm/sexdoll
[-] Askvoprosy: Увы!
[-] Astraclub: Увы!
[-] Astralinux: Увы!
[-] Au.ru: Увы!
[-] Audiojungle: Увы!
🇮🇳  AuthorSTREAM: http://www.authorstream.com/sexdoll/
[-] Author_today: Увы!
[-] Autokadabra: Увы!
[-] Autolada: Увы!
[-] Avizo: Увы!
[-] B17: Увы!
[-] BLIPfm: Увы!
[-] Baby: Увы!
[-] Babyblog: Увы!
[-] Backdoor_sdslabs: Увы!
🌎  Badoo: https://badoo.com/profile/sexdoll
🇺🇸  Bandcamp: https://www.bandcamp.com/sexdoll
[-] Barnacl: Увы!
[-] Bazar.cz: Увы!
[-] Bbiz_club: Увы!
[-] Bdoforumtr: Увы!
[-] Beerintheevening: Увы!
🇺🇸  Behance: https://www.behance.net/sexdoll
[-] Bibsonomy: Увы!
[-] Bigsoccer: Увы!
[-] Bikepost: Увы!
[-] BitBucket: Увы!
[-] BitCoinForum: Увы!
[-] Blackhatprotools: Увы!
[-] BleachFandom: Увы!
[-] Blog_7ya: Увы!
🌎  Blogger: https://sexdoll.blogspot.com
[-] Blogmarks: Увы!
[-] Boardgamegeek: Увы!
[-] BodyBuilding: Увы!
🇺🇸  Bookcrossing: https://www.bookcrossing.com/mybookshelf/sexdoll/
[-] Boxing: Увы!
[-] Bukkit: Увы!
[-] Buymeacoffee: Увы!
[-] BuzzFeed: Увы!
[-] CNET: Увы!
🇺🇸  Carbonmade: https://sexdoll.carbonmade.com
[-] Carder: Увы!
[-] Cardingforum: Увы!
[-] Cardingsite: Увы!
[-] Career_habr: Увы!
[-] Ccdi: Увы!
[-] Ccmixter: Увы!
[-] Cent: Увы!
[-] Cfd-online: Увы!
[-] Championat: Увы!
[-] Chan4chan: Увы!
[-] Chatujme: Увы!
[-] Cheezburger: Увы!
🌎  Chess: https://www.chess.com/ru/member/sexdoll
[-] Ошибка соединения: Chevrolet-cruze-club
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.6/ssl.py", line 900, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.6/ssl.py", line 864, in _check_connected
    self.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.6/ssl.py", line 900, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.6/ssl.py", line 864, in _check_connected
    self.getpeername()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "snoop.py", line 152, in get_response
    rsp = request_future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "snoop.py", line 1142, in main
    color=not args.no_func)
  File "snoop.py", line 322, in snoop
    color=color)
  File "snoop.py", line 163, in get_response
    gebb()            
  File "snoop.py", line 162, in gebb
    print_error(errc, "Ошибка соединения:", social_network, verbose, color)
  File "snoop.py", line 105, in print_error
    playsound('err.wav')
  File "/usr/local/lib/python3.6/dist-packages/playsound.py", line 92, in _playsoundNix
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "snoop.py", line 152, in get_response
    rsp = request_future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.chevrolet-cruze-club.ru', port=80): Max retries exceeded with url: /forum/member.php?username=sexdoll (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6ebc5fcc18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "snoop.py", line 1305, in <module>
    main()
  File "snoop.py", line 1151, in main
    color=not args.no_func)
  File "snoop.py", line 322, in snoop
    color=color)
  File "snoop.py", line 163, in get_response
    gebb()            
  File "snoop.py", line 162, in gebb
    print_error(errc, "Ошибка соединения:", social_network, verbose, color)
  File "snoop.py", line 105, in print_error
    playsound('err.wav')
  File "/usr/local/lib/python3.6/dist-packages/playsound.py", line 92, in _playsoundNix
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available```

**Comment by snooppr** [comment]
What OS did you run the question first?
Did you install the dependencies according to the instructions?

Have you tried the version for Termux on the OS on which you are crashing?
`git clone https://github.com/snooppr/snoop -b termux`

Note. Help (for future reference) tells you to enable the '-t' option.
You start without this option.

Linux?
`dpkg -l | grep libgstreamer`

**Comment by wanghaisheng** [comment]
ubuntu 18.04

**Comment by snooppr** [comment]
Can you upgrade your python3.6 to version 3.7? and try restarting again
`python3 snoop.py -t 9 username`

**Comment by alfabuster** [comment]
Same problems here. But I use Ubuntu 20.04 and Python 3.8.2 all dependencies are installed.

**Comment by snooppr** [comment]
add 

> libgstreamer-plugins-bad1.0-0:amd64

But this of course is weak for snoop.
You built python3 yourself (make)? Or put your own repository?

**Comment by snooppr** [comment]
@alfabuster @wanghaisheng 
I merged branches, you can do
`python3 snoop.py --update y`
Verify that you no longer have errors.  I will close issues.

**Comment by alfabuster** [comment]
> @alfabuster @wanghaisheng
> I merged branches, you can do
> `python3 snoop.py --update y`
> Verify that you no longer have errors. I will close issues.

Now it works fine. Good job, thank you!
