### ISSUE TITLE
NameError: name 'progress' is not defined

### ISSUE THREAD

**Issue by Shazgul** [snooppr/snoop#33]
Getting this Error after starting Snoop, any suggestions?

```
............[-] My_mail_ru_new: Недопустимый формат имени для данного сайта
............[-] My_mail_ru_old: Недопустимый формат имени для данного сайта
[-] 3dnews: Увы!
──────   1%
Traceback (most recent call last):
  File "snoop.py", line 1557, in <module>
    run()
  File "snoop.py", line 1362, in run
    color=not args.no_func)
  File "snoop.py", line 392, in snoop
    for social_network, net_info in progress1.track(site_data.items(), description=""):
  File "C:\Python3\lib\site-packages\rich\progress.py", line 710, in track
    progress.refresh()
NameError: name 'progress' is not defined
```

**Comment by snooppr** [comment]
You installed Snoop from source, the new rich library has a fatal error. I rolled back the rich version of the library to stable (rich verssion 1.2.3).
Thanks for your feedback.

Your solution to the problem:
`pip3 install rich == 1.2.3`
After installation, check the module version
`pip3 freeze | grep rich # must be version 1.2.3`
