### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by Drauggy** [snooppr/snoop#39]
На termux вот такое:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "snoop.py", line 1557, in <module>
    run()
  File "snoop.py", line 1352, in run
    results = snoop(username,
  File "snoop.py", line 280, in snoop
    session1 = ElapsedFuturesSession(executor=ProcessPoolExecutor(max_workers=30), session=my_session)
  File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

Насколько я понял, андроид не поддерживает семафоры. Как запускать?

**Comment by snooppr** [comment]
Спасибо за репорт!
Обновите snoop
`python snoop.py --update y`
И проверьте еще раз 
fix: https://github.com/snooppr/snoop/commit/dbc8801868e735893906d58ea8bb777a9b5d1d26

**Comment by Drauggy** [comment]
Сделал так, как вы написали. Ошибка та же
Сделал потом вручную git pull, все up to date

=======================
Вы действительно хотите:
                    __             _
   ._  _| _._|_ _  (_ ._  _  _ ._   )
|_||_)(_|(_| |_(/_ __)| |(_)(_)|_) o
   |                           |
нажмите 'y' y
Функция обновления Snoop требует установки <Git> на OS GNU/Linux
No local changes to save
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), 342 bytes | 42.00 KiB/s, done.
From https://github.com/snooppr/snoop
   400c754..dbc8801  master     -> origin/master
Updating 400c754..dbc8801
Fast-forward
 snoop.py | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)
=======================



Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "snoop.py", line 1560, in <module>
    run()
  File "snoop.py", line 1355, in run
    results = snoop(username,
  File "snoop.py", line 283, in snoop
    session1 = ElapsedFuturesSession(executor=ProcessPoolExecutor(max_workers=30), session=my_session)
  File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by snooppr** [comment]
Вы обновились?

> Сделал так, как вы написали. Ошибка та же

Я проверил на новом устройстве Android.
Ошибка исправлена, которую вы приложили в первом посте.

**Comment by Drauggy** [comment]
Да, андроид. Обновился командой python snoop.py --update y
Логи обновления выше приложил, фикс подтянулся, но ошибка та же. Проверил еще раз, все up to date.


Snoop: ('64bit', '')
snoop.py: 1.2.3A_rus Snoop (source demo)
OS: Linux-4.14.113-19542039-aarch64-with-libc
Python: 3.8.6

**Comment by snooppr** [comment]
добавил для arm64.
Обновитесь, проверьте.

По проблеме обновления:
Да, Termux обновился и git,
но вы можете не вручную обновляться, а по команде
`python snoop --update y`
Перед этим сделать, как написано в документации snoop:
```
Termux:
любой email, любое имя.
$ git config --global user.email "you@example.com"
$ git config --global user.name "username"
```

**Comment by Drauggy** [comment]
Спасибо! Обновился, все работает!
